from contextlib import suppress
from typing import List, Set
import logging

# core device drivers
from artiq.coredevice.core import Core
from artiq.coredevice.ad9910 import AD9910 # This is per ch
from artiq.coredevice.urukul import CPLD # This is the whole urukul controller
from artiq.coredevice.ttl import TTLOut
from artiq.coredevice.zotino import Zotino
from artiq.coredevice.suservo import Channel
from artiq.coredevice.suservo import SUServo
from artiq.coredevice.sampler import Sampler

# artiq
from artiq.language.units import MHz, dB, s, ms, us, V
from artiq.language.core import delay, kernel, rpc

# ndscan concepts
from ndscan.experiment.parameters import FloatParam, FloatParamHandle
from ndscan.experiment import Fragment, ExpFragment, OpaqueChannel
from ndscan.experiment import make_fragment_scan_exp

logger = logging.getLogger(__name__)

def is_ttl_name(s: str) -> bool:
    """
    Check whether a name is likely a hardware TTL (autogenerated),
    assumes <100 TTLs."""
    return s.startswith("ttl") and len(s) > 3 and len(s) < 6 and s[3:].isdigit()


class InitialiseHardware(Fragment):
    """
    Discover and init all hardware once per scan run.
    Has method `safe_off_initial_state` to start hardware in safe state.
    """

    def build_fragment(self):
        self.setattr_device("core")
        self.core: Core

        # host-side guard (survives host_setup being called again on resume)
        self._did_rtio_init = False


        db = self.get_device_db()

        # Discover devices by class name from device_db
        urukul_cpld_names: List[str] = []
        ad9910_names: List[str] = []
        suservo_names: List[str] = []
        suservo_channel_names: List[str] = []
        zotino_names: List[str] = []
        sampler_names: List[str] = []
        ttl_names: List[str] = []

        for name, desc in db.items():
            if not isinstance(desc, (dict)):
                continue
            try:
                cls = desc.get("class", "")
                if cls == "CPLD":
                    urukul_cpld_names.append(name)
                elif cls == "AD9910":
                    ad9910_names.append(name)
                elif cls == "SUServo":
                    suservo_names.append(name)
                elif cls == "Channel":
                    suservo_channel_names.append(name)
                elif cls == "Zotino":
                    zotino_names.append(name)
                elif cls == "Sampler":
                    sampler_names.append(name)
                elif is_ttl_name(name) and cls == "TTLOut":
                    ttl_names.append(name)

            except Exception:
                pass

        # Resolve to device objects (host-side)
        self.urukul_cplds: List[CPLD] = [self.get_device(n) for n in urukul_cpld_names]
        self.ad9910s: List[AD9910] = [self.get_device(n) for n in ad9910_names]
        self.suservos: List[SUServo] = [self.get_device(n) for n in suservo_names]
        self.suservo_channels: List[SUServo] = [self.get_device(n) for n in suservo_channel_names]
        self.zotinos: List[Zotino] = [self.get_device(n) for n in zotino_names]
        self.samplers: List[Sampler] = [self.get_device(n) for n in sampler_names]
        self.ttls: List[TTLOut] = [self.get_device(n) for n in ttl_names]

        kernel_invariants = getattr(self, "kernel_invariants", set())
        self.kernel_invariants = kernel_invariants | {
            "urukul_cplds", "ad9910s", "suservos", "suservo_channels", "zotinos", "samplers", "ttls"
        }

    def host_setup(self):
        super().host_setup()

        if self._did_rtio_init:
            return
        self._did_rtio_init = True


        logger.info("Init: %d CPLDs, %d AD9910, %d SUServo, %d Zotino, %d Samplers",
                    len(self.urukul_cplds), len(self.ad9910s),
                    len(self.suservos), len(self.zotinos), len(self.samplers))

        # Run the actual init once on the core
        self.rtio_init_all()

    @kernel
    def rtio_init_all(self):
        self.core.break_realtime()

        # Initialise CPLDs of the non-suservo ad9910 chips first.
        #  Resets the DDS I/O interface.
        for cpld in self.urukul_cplds:
            cpld.init()

        # Then DDS channels
        for dds in self.ad9910s:
            dds.init()

        # SUServo devices
        # Initializes the servo, Sampler and both Urukuls (and their cplds).
        # Leaves the servo disabled (see :meth:`set_config`), resets and
        # configures all DDS.
        for suservo in self.suservos:
            suservo.init()

        # DACs
        # Configures the SPI bus, drives LDAC and CLR high, programmes
        # the offset DACs, and enables overtemperature shutdown.
        for zotino in self.zotinos:
            zotino.init()

        # Samplers (Doesn't include SUServo samplers)
        # Initialize the device. Sets up SPI channels.
        for sampler in self.samplers:
            sampler.init()
    
    @kernel
    def safe_off_initial_state(self):
        
        for ttl in self.ttls:
            ttl.off()

        for dds in self.ad9910s:
            dds.sw.off()
            dds.set_profile(0)
            dds.set_att(0*dB)
            dds.set(10*MHz, amplitude = 0.0, profile=0)

        for zotino in self.zotinos:
            zotino.set_dac([0.0]*32)
        
        for channel in self.suservo_channels:
            channel.set(en_out=0, en_iir=0, profile=0)
            delay(3*us)
            channel.set_y(profile=0, y=0.)
