from typing import List, Set
import logging

# core device drivers
from artiq.coredevice.core import Core
from artiq.coredevice.ad9910 import AD9910 # This is per ch
from artiq.coredevice.urukul import CPLD # This is the whole urukul controller
from artiq.coredevice.ttl import TTLOut
from artiq.coredevice.zotino import Zotino
from artiq.coredevice.suservo import Channel, SUServo
from artiq.coredevice.sampler import Sampler

# artiq
from artiq.language.units import MHz, dB, us, V
from artiq.language.core import delay, kernel, delay_mu

# ndscan concepts
from ndscan.experiment import Fragment

logger = logging.getLogger(__name__)

def is_ttl_name(s: str) -> bool:
    """
    Check whether a name is likely a hardware TTL (autogenerated),
    assumes <100 TTLs.
    """
    return s.startswith("ttl") and len(s) > 3 and len(s) < 6 and s[3:].isdigit()


class InitialiseHardware(Fragment):
    """
    Discover and initialise hardware once per scan run.

    Important:
      - Stand-alone Urukul DDS/CPLDs are kept separate from SUServo-owned DDS/CPLDs.
      - They are initialized in separate kernels so the ARTIQ compiler does not have
        to unify incompatible AD9910/CPLD object layouts.
    
    Has method `safe_off_initial_state` to start hardware in safe state.
    """


    def build_fragment(self):
        self.setattr_device("core")
        self.core: Core

        self._did_rtio_init = False

        kernel_invariants = getattr(self, "kernel_invariants", set())
        self.kernel_invariants = kernel_invariants | {
            "standalone_urukul_cplds",
            "standalone_ad9910s",
            "standalone_sw_ad9910s",
            "suservos",
            "suservo_channels",
            "zotinos",
            "samplers",
            "ttls",
        }

    def host_setup(self):
        super().host_setup()

        if self._did_rtio_init:
            return
        self._did_rtio_init = True

        self._discover_devices()

        print(
            "Init: %d standalone CPLDs, %d standalone AD9910, %d SUServo, %d SUServo channels, %d Zotino, %d Samplers, %d TTLs",
            len(self.standalone_urukul_cplds),
            len(self.standalone_ad9910s),
            len(self.suservos),
            len(self.suservo_channels),
            len(self.zotinos),
            len(self.samplers),
            len(self.ttls),
        )

        # Separate kernel entry points: do NOT wrap these in one umbrella kernel.
        self.rtio_init_standalone()
        # self.rtio_init_suservos()

    def _discover_devices(self):
        db = self.get_device_db()

        # First collect which DDS/CPLDs are owned by SUServo.
        suservo_dds_names: Set[str] = set()
        suservo_cpld_names: Set[str] = set()

        suservo_names: List[str] = []
        suservo_channel_names: List[str] = []
        zotino_names: List[str] = []
        sampler_names: List[str] = []
        ttl_names: List[str] = []

        for name, desc in db.items():
            if not isinstance(desc, dict):
                continue

            cls = desc.get("class", "")
            args = desc.get("arguments", {}) or {}

            if cls == "SUServo":
                suservo_names.append(name)

                for dds_name in args.get("dds_devices", []):
                    suservo_dds_names.add(dds_name)

                for cpld_name in args.get("cpld_devices", []):
                    suservo_cpld_names.add(cpld_name)

            elif cls == "Channel":
                suservo_channel_names.append(name)

            elif cls == "Zotino":
                zotino_names.append(name)

            elif cls == "Sampler":
                sampler_names.append(name)

            elif cls == "TTLOut" and is_ttl_name(name):
                ttl_names.append(name)

        # Now collect only stand-alone Urukul devices.
        standalone_cpld_names: List[str] = []
        standalone_ad9910_names: List[str] = []

        for name, desc in db.items():
            if not isinstance(desc, dict):
                continue

            cls = desc.get("class", "")
            args = desc.get("arguments", {}) or {}

            if cls == "CPLD" and name not in suservo_cpld_names:
                standalone_cpld_names.append(name)

            elif cls == "AD9910" and name not in suservo_dds_names:
                standalone_ad9910_names.append(name)

        # Resolve host-side device objects
        self.standalone_urukul_cplds: List[CPLD] = [
            self.get_device(n) for n in standalone_cpld_names
        ]
        self.standalone_ad9910s: List[AD9910] = [
            self.get_device(n) for n in standalone_ad9910_names
        ]

        self.suservos = [self.get_device(n) for n in suservo_names]
        self.suservo_channels = [
            self.get_device(n) for n in suservo_channel_names
        ]
        self.zotinos: List[Zotino] = [self.get_device(n) for n in zotino_names]
        self.samplers: List[Sampler] = [self.get_device(n) for n in sampler_names]
        self.ttls: List[TTLOut] = [self.get_device(n) for n in ttl_names]

    @kernel
    def rtio_init_standalone(self):
        self.core.reset()

        # Stand-alone Urukul CPLDs first.
        for cpld in self.standalone_urukul_cplds:
            cpld.init()

        self.core.break_realtime()
        # Then stand-alone DDS channels.
        for dds in self.standalone_ad9910s:
            dds.init()

        self.core.break_realtime()
        # DACs
        for zotino in self.zotinos:
            zotino.init()

        self.core.break_realtime()
        # Non-SUServo samplers
        for sampler in self.samplers:
            sampler.init()

    @kernel
    def rtio_init_suservos(self):
        self.core.break_realtime()

        # SUServo.init() internally touches its own CPLDs and DDSes.
        for suservo in self.suservos:
            suservo.init()

    @kernel
    def safe_off_standalone(self):
        for ttl in self.ttls:
            ttl.off()
            delay_mu(8)

        for dds in self.standalone_ad9910s:
            dds.sw.off()
            dds.set_profile(0)
            delay(2*us)
            # dds.set_att(0 * dB)
            # dds.set(10 * MHz, amplitude=0.0, profile=0)
            # delay_mu(16)

        # for zotino in self.zotinos:
        #     zotino.set_dac([0.0] * 32)

    @kernel
    def safe_off_suservo(self):
        self.core.break_realtime()

        # Safest route before set_y(): stop servo iterations first.
        for suservo in self.suservos:
            suservo.set_config(enable=0)
        delay(3 * us)

        for channel in self.suservo_channels:
            channel.set(en_out=0, en_iir=0, profile=0)
        delay(3 * us)

        for channel in self.suservo_channels:
            channel.set_y(profile=0, y=0.0)





















"""
    def build_fragment(self):
        self.setattr_device("core")
        self.core: Core

        self._did_rtio_init = False

        kernel_invariants = getattr(self, "kernel_invariants", set())
        self.kernel_invariants = kernel_invariants | {
            "standalone_urukul_cplds",
            "standalone_ad9910s",
            "standalone_sw_ad9910s",
            "suservos",
            "suservo_channels",
            "zotinos",
            "samplers",
            "ttls",
        }

    def host_setup(self):
        super().host_setup()

        if self._did_rtio_init:
            return
        self._did_rtio_init = True


        logger.info("Init: %d CPLDs, %d AD9910, %d SUServo, %d Zotino, %d Samplers",
                    len(self.urukul_cplds), len(self.ad9910s),
                    len(self.suservos), len(self.zotinos), len(self.samplers))

        # Run the actual init once on the core
        self.rtio_init_all()

    @kernel
    def rtio_init_all(self):
        self.core.break_realtime()

        # Initialise CPLDs of the non-suservo ad9910 chips first.
        #  Resets the DDS I/O interface.
        for cpld in self.urukul_cplds:
            cpld.init()

        # Then DDS channels
        for dds in self.ad9910s:
            dds.init()

        # SUServo devices
        # Initializes the servo, Sampler and both Urukuls (and their cplds).
        # Leaves the servo disabled (see :meth:`set_config`), resets and
        # configures all DDS.
        for suservo in self.suservos:
            suservo.init()

        # DACs
        # Configures the SPI bus, drives LDAC and CLR high, programmes
        # the offset DACs, and enables overtemperature shutdown.
        for zotino in self.zotinos:
            zotino.init()

        # Samplers (Doesn't include SUServo samplers)
        # Initialize the device. Sets up SPI channels.
        for sampler in self.samplers:
            sampler.init()
    
    @kernel
    def safe_off_initial_state(self):
        
        for ttl in self.ttls:
            ttl.off()

        for dds in self.ad9910s:
            dds.sw.off()
            dds.set_profile(0)
            dds.set_att(0*dB)
            dds.set(10*MHz, amplitude = 0.0, profile=0)

        for zotino in self.zotinos:
            zotino.set_dac([0.0]*32)
        
        for channel in self.suservo_channels:
            channel.set(en_out=0, en_iir=0, profile=0)
            delay(3*us)
            channel.set_y(profile=0, y=0.)
"""